services:
  - type: web
    name: laravel-app
    runtime: docker
    repo: https://github.com/ChiniHendi2004/final_auth_by_me
    region: oregon
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: bzxhtuvciazryty89hmi-mysql.services.clever-cloud.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: bzxhtuvciazryty89hmi
      - key: DB_USERNAME
        value: uwtaonrjqeaqelut
      - key: DB_PASSWORD
        value: YG5S7RC6YdU5E5JNJjGP
