services:
  - type: web
    name: laravel-app
    runtime: docker
    repo: https://github.com/ChiniHendi2004/doctor_appointment_apis
    region: oregon
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: bwuizwmonubhwvcnlaxr-mysql.services.clever-cloud.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: bwuizwmonubhwvcnlaxr
      - key: DB_USERNAME
        value: u1fdwyyvqz6nlgtz
      - key: DB_PASSWORD
        value: pv8mYwOnbkjRQYnzVLqC
